-- OpenHub initial schema (PostgreSQL)
-- Generated by scripts/write-init-migration.mjs from prisma/schema.prisma.
-- Apply with: npx prisma migrate deploy
CREATE TABLE "User" (
  "id" TEXT PRIMARY KEY,
  "email" TEXT NOT NULL,
  "username" TEXT NOT NULL,
  "passwordHash" TEXT NOT NULL,
  "role" TEXT NOT NULL DEFAULT 'user',
  "emailVerified" TIMESTAMP(3),
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "isSuspended" BOOLEAN NOT NULL DEFAULT false,
  "suspendedReason" TEXT,
  "locale" TEXT NOT NULL DEFAULT 'en',
  "theme" TEXT NOT NULL DEFAULT 'system',
  "lastLoginAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "deletedAt" TIMESTAMP(3),
  UNIQUE ("email"),
  UNIQUE ("username")
);

CREATE TABLE "Role" (
  "id" TEXT PRIMARY KEY,
  "key" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "isSystem" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("key")
);

CREATE TABLE "Permission" (
  "id" TEXT PRIMARY KEY,
  "key" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  UNIQUE ("key")
);

CREATE TABLE "RolePermission" (
  "id" TEXT PRIMARY KEY,
  "roleId" TEXT NOT NULL,
  "permissionId" TEXT NOT NULL,
  UNIQUE ("roleId", "permissionId"),
  FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("permissionId") REFERENCES "Permission"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Account" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "provider" TEXT NOT NULL,
  "providerAccountId" TEXT NOT NULL,
  "accessToken" TEXT,
  "refreshToken" TEXT,
  "expiresAt" TIMESTAMP(3),
  UNIQUE ("provider", "providerAccountId"),
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Session" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "tokenHash" TEXT NOT NULL,
  "userAgent" TEXT,
  "ipHash" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "expiresAt" TIMESTAMP(3) NOT NULL,
  "revokedAt" TIMESTAMP(3),
  UNIQUE ("tokenHash"),
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Profile" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "displayName" TEXT NOT NULL,
  "avatarUrl" TEXT,
  "bio" TEXT,
  "city" TEXT,
  "country" TEXT,
  "latitude" DOUBLE PRECISION,
  "longitude" DOUBLE PRECISION,
  "userTypes" TEXT NOT NULL DEFAULT '',
  "availability" TEXT,
  "verificationStatus" TEXT NOT NULL DEFAULT 'unverified',
  "verifiedAt" TIMESTAMP(3),
  "verifiedById" TEXT,
  "helpfulnessScore" INTEGER NOT NULL DEFAULT 0,
  "profileVisibility" TEXT NOT NULL DEFAULT 'public',
  "showLocation" BOOLEAN NOT NULL DEFAULT false,
  "showOnlineStatus" BOOLEAN NOT NULL DEFAULT false,
  "showActivity" BOOLEAN NOT NULL DEFAULT true,
  "searchable" BOOLEAN NOT NULL DEFAULT true,
  "allowMessages" TEXT NOT NULL DEFAULT 'everyone',
  "showGroupMembership" BOOLEAN NOT NULL DEFAULT true,
  "website" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  UNIQUE ("userId"),
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("verifiedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "Tag" (
  "id" TEXT PRIMARY KEY,
  "kind" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  UNIQUE ("kind", "slug")
);

CREATE TABLE "UserTag" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "tagId" TEXT NOT NULL,
  "level" TEXT,
  UNIQUE ("userId", "tagId"),
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("tagId") REFERENCES "Tag"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "DashboardPreference" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "layout" TEXT NOT NULL DEFAULT 'comfortable',
  "defaultModule" TEXT NOT NULL DEFAULT 'dashboard',
  "widgets" TEXT NOT NULL DEFAULT '[]',
  "pinnedTools" TEXT NOT NULL DEFAULT '',
  "updatedAt" TIMESTAMP(3) NOT NULL,
  UNIQUE ("userId"),
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Group" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "description" TEXT,
  "avatarUrl" TEXT,
  "kind" TEXT NOT NULL DEFAULT 'friends',
  "visibility" TEXT NOT NULL DEFAULT 'private',
  "ownerId" TEXT NOT NULL,
  "archivedAt" TIMESTAMP(3),
  "deletedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  UNIQUE ("slug"),
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Task" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "groupId" TEXT,
  "assigneeId" TEXT,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "dueAt" TIMESTAMP(3),
  "priority" TEXT NOT NULL DEFAULT 'medium',
  "recurrence" TEXT NOT NULL DEFAULT 'none',
  "labels" TEXT NOT NULL DEFAULT '',
  "completedAt" TIMESTAMP(3),
  "archivedAt" TIMESTAMP(3),
  "deletedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("assigneeId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Subtask" (
  "id" TEXT PRIMARY KEY,
  "taskId" TEXT NOT NULL,
  "ownerId" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "position" INTEGER NOT NULL DEFAULT 0,
  "completedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("taskId") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Note" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL DEFAULT '',
  "tags" TEXT NOT NULL DEFAULT '',
  "pinned" BOOLEAN NOT NULL DEFAULT false,
  "archivedAt" TIMESTAMP(3),
  "deletedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Habit" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "frequency" TEXT NOT NULL DEFAULT 'daily',
  "targetCount" INTEGER NOT NULL DEFAULT 1,
  "archivedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "HabitLog" (
  "id" TEXT PRIMARY KEY,
  "habitId" TEXT NOT NULL,
  "day" TEXT NOT NULL,
  "count" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("habitId", "day"),
  FOREIGN KEY ("habitId") REFERENCES "Habit"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Bookmark" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "url" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "category" TEXT,
  "tags" TEXT NOT NULL DEFAULT '',
  "favorite" BOOLEAN NOT NULL DEFAULT false,
  "archivedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Trip" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "destination" TEXT,
  "startsAt" TIMESTAMP(3),
  "endsAt" TIMESTAMP(3),
  "visibility" TEXT NOT NULL DEFAULT 'private',
  "budgetCents" INTEGER,
  "currency" TEXT NOT NULL DEFAULT 'USD',
  "accommodationNotes" TEXT,
  "transportNotes" TEXT,
  "mapLinks" TEXT NOT NULL DEFAULT '',
  "importantContacts" TEXT,
  "deletedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "CalendarEvent" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "groupId" TEXT,
  "tripId" TEXT,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "location" TEXT,
  "startsAt" TIMESTAMP(3) NOT NULL,
  "endsAt" TIMESTAMP(3),
  "allDay" BOOLEAN NOT NULL DEFAULT false,
  "reminderMinutes" INTEGER,
  "recurrence" TEXT NOT NULL DEFAULT 'none',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "GroupMember" (
  "id" TEXT PRIMARY KEY,
  "groupId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "role" TEXT NOT NULL DEFAULT 'member',
  "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "lastReadAt" TIMESTAMP(3),
  UNIQUE ("groupId", "userId"),
  FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "GroupInvitation" (
  "id" TEXT PRIMARY KEY,
  "groupId" TEXT NOT NULL,
  "email" TEXT,
  "token" TEXT NOT NULL,
  "role" TEXT NOT NULL DEFAULT 'member',
  "invitedById" TEXT NOT NULL,
  "message" TEXT,
  "expiresAt" TIMESTAMP(3),
  "acceptedAt" TIMESTAMP(3),
  "revokedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("token"),
  FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("invitedById") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "GroupJoinRequest" (
  "id" TEXT PRIMARY KEY,
  "groupId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "message" TEXT,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "reviewedById" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("groupId", "userId"),
  FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "GroupPost" (
  "id" TEXT PRIMARY KEY,
  "groupId" TEXT NOT NULL,
  "authorId" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL DEFAULT '',
  "kind" TEXT NOT NULL DEFAULT 'post',
  "pinned" BOOLEAN NOT NULL DEFAULT false,
  "locked" BOOLEAN NOT NULL DEFAULT false,
  "hiddenAt" TIMESTAMP(3),
  "deletedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "ShoppingItem" (
  "id" TEXT PRIMARY KEY,
  "groupId" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "quantity" TEXT,
  "addedById" TEXT NOT NULL,
  "purchasedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("addedById") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "HelpRequest" (
  "id" TEXT PRIMARY KEY,
  "authorId" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "tags" TEXT NOT NULL DEFAULT '',
  "kind" TEXT NOT NULL DEFAULT 'question',
  "urgency" TEXT NOT NULL DEFAULT 'normal',
  "visibility" TEXT NOT NULL DEFAULT 'public',
  "city" TEXT,
  "country" TEXT,
  "status" TEXT NOT NULL DEFAULT 'open',
  "acceptedResponseId" TEXT,
  "lockedAt" TIMESTAMP(3),
  "hiddenAt" TIMESTAMP(3),
  "deletedAt" TIMESTAMP(3),
  "views" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "HelpResponse" (
  "id" TEXT PRIMARY KEY,
  "requestId" TEXT NOT NULL,
  "authorId" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "isAccepted" BOOLEAN NOT NULL DEFAULT false,
  "hiddenAt" TIMESTAMP(3),
  "deletedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("requestId") REFERENCES "HelpRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Comment" (
  "id" TEXT PRIMARY KEY,
  "authorId" TEXT NOT NULL,
  "targetType" TEXT NOT NULL,
  "targetId" TEXT NOT NULL,
  "parentId" TEXT,
  "body" TEXT NOT NULL,
  "hiddenAt" TIMESTAMP(3),
  "deletedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Vote" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "targetType" TEXT NOT NULL,
  "targetId" TEXT NOT NULL,
  "value" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("userId", "targetType", "targetId"),
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Subject" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "level" TEXT NOT NULL DEFAULT 'other',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("name")
);

CREATE TABLE "StudentResource" (
  "id" TEXT PRIMARY KEY,
  "uploaderId" TEXT NOT NULL,
  "subjectId" TEXT,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "level" TEXT NOT NULL DEFAULT 'other',
  "language" TEXT NOT NULL DEFAULT 'en',
  "difficulty" TEXT NOT NULL DEFAULT 'beginner',
  "fileType" TEXT NOT NULL DEFAULT 'notes',
  "institution" TEXT,
  "tags" TEXT NOT NULL DEFAULT '',
  "url" TEXT,
  "fileId" TEXT,
  "downloads" INTEGER NOT NULL DEFAULT 0,
  "verified" BOOLEAN NOT NULL DEFAULT false,
  "copyrightFlags" INTEGER NOT NULL DEFAULT 0,
  "hiddenAt" TIMESTAMP(3),
  "deletedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("uploaderId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "FlashcardDeck" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "subjectId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Flashcard" (
  "id" TEXT PRIMARY KEY,
  "deckId" TEXT NOT NULL,
  "ownerId" TEXT NOT NULL,
  "front" TEXT NOT NULL,
  "back" TEXT NOT NULL,
  "hint" TEXT,
  "repetitions" INTEGER NOT NULL DEFAULT 0,
  "easeFactor" INTEGER NOT NULL DEFAULT 250,
  "intervalDays" INTEGER NOT NULL DEFAULT 0,
  "nextReviewAt" TIMESTAMP(3),
  "lastReviewedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("deckId") REFERENCES "FlashcardDeck"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Assignment" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "subjectId" TEXT,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "dueAt" TIMESTAMP(3) NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "weightPct" DOUBLE PRECISION,
  "scorePct" DOUBLE PRECISION,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "Exam" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "subjectId" TEXT,
  "title" TEXT NOT NULL,
  "examAt" TIMESTAMP(3) NOT NULL,
  "location" TEXT,
  "notes" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "TimetableSlot" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "subjectId" TEXT,
  "title" TEXT NOT NULL,
  "dayOfWeek" INTEGER NOT NULL,
  "startTime" TEXT NOT NULL,
  "endTime" TEXT NOT NULL,
  "room" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("subjectId") REFERENCES "Subject"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "CourseGrade" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "credits" DOUBLE PRECISION NOT NULL DEFAULT 3,
  "gradePoint" DOUBLE PRECISION NOT NULL DEFAULT 4,
  "term" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Listing" (
  "id" TEXT PRIMARY KEY,
  "kind" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "organization" TEXT,
  "description" TEXT NOT NULL,
  "url" TEXT,
  "location" TEXT,
  "amountCents" INTEGER,
  "currency" TEXT NOT NULL DEFAULT 'USD',
  "deadline" TIMESTAMP(3),
  "level" TEXT,
  "country" TEXT,
  "tags" TEXT NOT NULL DEFAULT '',
  "verified" BOOLEAN NOT NULL DEFAULT false,
  "published" BOOLEAN NOT NULL DEFAULT true,
  "createdById" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "Skill" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "category" TEXT,
  "description" TEXT,
  UNIQUE ("name"),
  UNIQUE ("slug")
);

CREATE TABLE "SkillOffer" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "skillId" TEXT NOT NULL,
  "level" TEXT NOT NULL DEFAULT 'intermediate',
  "format" TEXT NOT NULL DEFAULT 'both',
  "description" TEXT,
  "availability" TEXT,
  "language" TEXT NOT NULL DEFAULT 'en',
  "city" TEXT,
  "country" TEXT,
  "radiusKm" INTEGER,
  "priceMode" TEXT NOT NULL DEFAULT 'exchange',
  "priceCents" INTEGER,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("skillId") REFERENCES "Skill"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "SkillRequest" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "skillId" TEXT NOT NULL,
  "level" TEXT NOT NULL DEFAULT 'beginner',
  "format" TEXT NOT NULL DEFAULT 'both',
  "description" TEXT,
  "availability" TEXT,
  "language" TEXT NOT NULL DEFAULT 'en',
  "city" TEXT,
  "country" TEXT,
  "radiusKm" INTEGER,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("skillId") REFERENCES "Skill"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "SkillConnection" (
  "id" TEXT PRIMARY KEY,
  "offerId" TEXT,
  "requestId" TEXT,
  "fromUserId" TEXT NOT NULL,
  "toUserId" TEXT NOT NULL,
  "message" TEXT,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "meetingAt" TIMESTAMP(3),
  "meetingNote" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("offerId") REFERENCES "SkillOffer"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("requestId") REFERENCES "SkillRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("fromUserId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("toUserId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "SkillReview" (
  "id" TEXT PRIMARY KEY,
  "connectionId" TEXT,
  "reviewerId" TEXT NOT NULL,
  "revieweeId" TEXT NOT NULL,
  "rating" INTEGER NOT NULL,
  "comment" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("connectionId", "reviewerId"),
  FOREIGN KEY ("connectionId") REFERENCES "SkillConnection"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("reviewerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("revieweeId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "LocalResource" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "description" TEXT,
  "address" TEXT,
  "city" TEXT,
  "country" TEXT,
  "latitude" DOUBLE PRECISION,
  "longitude" DOUBLE PRECISION,
  "phone" TEXT,
  "website" TEXT,
  "openingHours" TEXT,
  "accessibility" TEXT,
  "priceLevel" INTEGER NOT NULL DEFAULT 0,
  "verified" BOOLEAN NOT NULL DEFAULT false,
  "verifiedById" TEXT,
  "verifiedAt" TIMESTAMP(3),
  "lastConfirmedAt" TIMESTAMP(3),
  "submittedById" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "hiddenAt" TIMESTAMP(3),
  "deletedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("submittedById") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("verifiedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "ResourceReview" (
  "id" TEXT PRIMARY KEY,
  "resourceId" TEXT NOT NULL,
  "authorId" TEXT NOT NULL,
  "rating" INTEGER NOT NULL,
  "comment" TEXT,
  "hiddenAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("resourceId") REFERENCES "LocalResource"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "ResourceEditSuggestion" (
  "id" TEXT PRIMARY KEY,
  "resourceId" TEXT NOT NULL,
  "suggestedById" TEXT NOT NULL,
  "field" TEXT NOT NULL,
  "currentValue" TEXT,
  "proposedValue" TEXT NOT NULL,
  "note" TEXT,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "reviewedById" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("resourceId") REFERENCES "LocalResource"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("suggestedById") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "VolunteerOpportunity" (
  "id" TEXT PRIMARY KEY,
  "organizerId" TEXT NOT NULL,
  "organizationName" TEXT,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "cause" TEXT NOT NULL,
  "skillsNeeded" TEXT NOT NULL DEFAULT '',
  "itemsNeeded" TEXT NOT NULL DEFAULT '',
  "city" TEXT,
  "country" TEXT,
  "latitude" DOUBLE PRECISION,
  "longitude" DOUBLE PRECISION,
  "startsAt" TIMESTAMP(3),
  "deadline" TIMESTAMP(3),
  "volunteersNeeded" INTEGER NOT NULL DEFAULT 1,
  "status" TEXT NOT NULL DEFAULT 'open',
  "verified" BOOLEAN NOT NULL DEFAULT false,
  "verifiedById" TEXT,
  "hiddenAt" TIMESTAMP(3),
  "deletedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("organizerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "VolunteerSignup" (
  "id" TEXT PRIMARY KEY,
  "opportunityId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "message" TEXT,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("opportunityId", "userId"),
  FOREIGN KEY ("opportunityId") REFERENCES "VolunteerOpportunity"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "DonationCampaign" (
  "id" TEXT PRIMARY KEY,
  "organizerId" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "cause" TEXT NOT NULL,
  "kind" TEXT NOT NULL DEFAULT 'goods',
  "goalCents" INTEGER,
  "raisedCents" INTEGER NOT NULL DEFAULT 0,
  "itemsNeeded" TEXT NOT NULL DEFAULT '',
  "city" TEXT,
  "country" TEXT,
  "contactEmail" TEXT,
  "deadline" TIMESTAMP(3),
  "status" TEXT NOT NULL DEFAULT 'open',
  "verified" BOOLEAN NOT NULL DEFAULT false,
  "verifiedById" TEXT,
  "paymentProvider" TEXT,
  "hiddenAt" TIMESTAMP(3),
  "deletedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("organizerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "CampaignUpdate" (
  "id" TEXT PRIMARY KEY,
  "campaignId" TEXT NOT NULL,
  "authorId" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("campaignId") REFERENCES "DonationCampaign"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "BloodDonorProfile" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "bloodGroup" TEXT NOT NULL,
  "city" TEXT,
  "country" TEXT,
  "lastDonatedAt" TIMESTAMP(3),
  "contactPreference" TEXT NOT NULL DEFAULT 'message',
  "available" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  UNIQUE ("userId"),
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "EmergencyNumber" (
  "id" TEXT PRIMARY KEY,
  "country" TEXT NOT NULL,
  "region" TEXT,
  "service" TEXT NOT NULL,
  "number" TEXT NOT NULL,
  "notes" TEXT,
  "source" TEXT,
  "verified" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "EmergencyContact" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "relation" TEXT,
  "phone" TEXT NOT NULL,
  "isPrimary" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Guide" (
  "id" TEXT PRIMARY KEY,
  "slug" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "locale" TEXT NOT NULL DEFAULT 'en',
  "position" INTEGER NOT NULL DEFAULT 0,
  "published" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  UNIQUE ("slug")
);

CREATE TABLE "MissingPerson" (
  "id" TEXT PRIMARY KEY,
  "reportedById" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "age" INTEGER,
  "lastSeenAt" TIMESTAMP(3),
  "lastSeenLocation" TEXT,
  "description" TEXT NOT NULL,
  "contactNote" TEXT,
  "status" TEXT NOT NULL DEFAULT 'open',
  "verified" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("reportedById") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "BusinessProfile" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "description" TEXT,
  "logoUrl" TEXT,
  "address" TEXT,
  "city" TEXT,
  "country" TEXT,
  "phone" TEXT,
  "email" TEXT,
  "website" TEXT,
  "taxId" TEXT,
  "taxRateBp" INTEGER NOT NULL DEFAULT 0,
  "invoicePrefix" TEXT NOT NULL DEFAULT 'INV-',
  "invoiceCounter" INTEGER NOT NULL DEFAULT 0,
  "currency" TEXT NOT NULL DEFAULT 'USD',
  "qrMenuEnabled" BOOLEAN NOT NULL DEFAULT false,
  "published" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  UNIQUE ("ownerId"),
  UNIQUE ("slug"),
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Service" (
  "id" TEXT PRIMARY KEY,
  "businessId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "priceCents" INTEGER,
  "durationMinutes" INTEGER,
  "position" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("businessId") REFERENCES "BusinessProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Customer" (
  "id" TEXT PRIMARY KEY,
  "businessId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "email" TEXT,
  "phone" TEXT,
  "address" TEXT,
  "notes" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("businessId") REFERENCES "BusinessProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "InventoryItem" (
  "id" TEXT PRIMARY KEY,
  "businessId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "sku" TEXT,
  "category" TEXT,
  "quantity" INTEGER NOT NULL DEFAULT 0,
  "unitCostCents" INTEGER NOT NULL DEFAULT 0,
  "priceCents" INTEGER NOT NULL DEFAULT 0,
  "reorderLevel" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("businessId") REFERENCES "BusinessProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Appointment" (
  "id" TEXT PRIMARY KEY,
  "businessId" TEXT NOT NULL,
  "serviceId" TEXT,
  "customerId" TEXT,
  "clientName" TEXT NOT NULL,
  "clientEmail" TEXT,
  "startsAt" TIMESTAMP(3) NOT NULL,
  "endsAt" TIMESTAMP(3),
  "status" TEXT NOT NULL DEFAULT 'pending',
  "notes" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("businessId") REFERENCES "BusinessProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "Invoice" (
  "id" TEXT PRIMARY KEY,
  "businessId" TEXT NOT NULL,
  "customerId" TEXT,
  "number" TEXT NOT NULL,
  "issueDate" TIMESTAMP(3) NOT NULL,
  "dueDate" TIMESTAMP(3),
  "status" TEXT NOT NULL DEFAULT 'draft',
  "currency" TEXT NOT NULL DEFAULT 'USD',
  "taxRateBp" INTEGER NOT NULL DEFAULT 0,
  "discountCents" INTEGER NOT NULL DEFAULT 0,
  "subtotalCents" INTEGER NOT NULL DEFAULT 0,
  "taxCents" INTEGER NOT NULL DEFAULT 0,
  "totalCents" INTEGER NOT NULL DEFAULT 0,
  "notes" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  UNIQUE ("businessId", "number"),
  FOREIGN KEY ("businessId") REFERENCES "BusinessProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "InvoiceItem" (
  "id" TEXT PRIMARY KEY,
  "invoiceId" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "quantity" DOUBLE PRECISION NOT NULL DEFAULT 1,
  "unitPriceCents" INTEGER NOT NULL DEFAULT 0,
  "totalCents" INTEGER NOT NULL DEFAULT 0,
  "position" INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "SaleRecord" (
  "id" TEXT PRIMARY KEY,
  "businessId" TEXT NOT NULL,
  "invoiceId" TEXT,
  "amountCents" INTEGER NOT NULL,
  "currency" TEXT NOT NULL DEFAULT 'USD',
  "method" TEXT,
  "soldAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "notes" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("businessId") REFERENCES "BusinessProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "CannedMessage" (
  "id" TEXT PRIMARY KEY,
  "businessId" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("businessId") REFERENCES "BusinessProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "TripMember" (
  "id" TEXT PRIMARY KEY,
  "tripId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "role" TEXT NOT NULL DEFAULT 'member',
  "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("tripId", "userId"),
  FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "ItineraryItem" (
  "id" TEXT PRIMARY KEY,
  "tripId" TEXT NOT NULL,
  "addedById" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "location" TEXT,
  "startsAt" TIMESTAMP(3),
  "endsAt" TIMESTAMP(3),
  "costCents" INTEGER,
  "position" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("addedById") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "PackingItem" (
  "id" TEXT PRIMARY KEY,
  "tripId" TEXT NOT NULL,
  "addedById" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "category" TEXT,
  "packedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("addedById") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Expense" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "groupId" TEXT,
  "tripId" TEXT,
  "businessId" TEXT,
  "category" TEXT NOT NULL,
  "description" TEXT,
  "amountCents" INTEGER NOT NULL,
  "currency" TEXT NOT NULL DEFAULT 'USD',
  "occurredOn" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "isShared" BOOLEAN NOT NULL DEFAULT false,
  "fileId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "ExpenseSplit" (
  "id" TEXT PRIMARY KEY,
  "expenseId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "shareCents" INTEGER NOT NULL DEFAULT 0,
  "settledAt" TIMESTAMP(3),
  UNIQUE ("expenseId", "userId"),
  FOREIGN KEY ("expenseId") REFERENCES "Expense"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Poll" (
  "id" TEXT PRIMARY KEY,
  "groupId" TEXT,
  "tripId" TEXT,
  "authorId" TEXT NOT NULL,
  "question" TEXT NOT NULL,
  "multi" BOOLEAN NOT NULL DEFAULT false,
  "closesAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "PollOption" (
  "id" TEXT PRIMARY KEY,
  "pollId" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "position" INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY ("pollId") REFERENCES "Poll"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "PollVote" (
  "id" TEXT PRIMARY KEY,
  "optionId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("optionId", "userId"),
  FOREIGN KEY ("optionId") REFERENCES "PollOption"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Conversation" (
  "id" TEXT PRIMARY KEY,
  "kind" TEXT NOT NULL DEFAULT 'direct',
  "groupId" TEXT,
  "title" TEXT,
  "lastMessageAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "ConversationParticipant" (
  "id" TEXT PRIMARY KEY,
  "conversationId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "lastReadAt" TIMESTAMP(3),
  "hiddenAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("conversationId", "userId"),
  FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Message" (
  "id" TEXT PRIMARY KEY,
  "conversationId" TEXT NOT NULL,
  "senderId" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "deletedAt" TIMESTAMP(3),
  "hiddenAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("senderId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Notification" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT,
  "targetType" TEXT,
  "targetId" TEXT,
  "link" TEXT,
  "readAt" TIMESTAMP(3),
  "emailedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "NotificationPreference" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "inAppEnabled" BOOLEAN NOT NULL DEFAULT true,
  "emailEnabled" BOOLEAN NOT NULL DEFAULT false,
  "digestMode" TEXT NOT NULL DEFAULT 'instant',
  "disabledTypes" TEXT NOT NULL DEFAULT '',
  "updatedAt" TIMESTAMP(3) NOT NULL,
  UNIQUE ("userId"),
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Report" (
  "id" TEXT PRIMARY KEY,
  "reporterId" TEXT NOT NULL,
  "targetType" TEXT NOT NULL,
  "targetId" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "details" TEXT,
  "status" TEXT NOT NULL DEFAULT 'open',
  "resolution" TEXT,
  "reviewedById" TEXT,
  "reviewedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("reporterId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("reviewedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "ModerationAction" (
  "id" TEXT PRIMARY KEY,
  "moderatorId" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "targetType" TEXT NOT NULL,
  "targetId" TEXT NOT NULL,
  "note" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("moderatorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "AuditLog" (
  "id" TEXT PRIMARY KEY,
  "actorId" TEXT,
  "actorEmail" TEXT,
  "action" TEXT NOT NULL,
  "targetType" TEXT,
  "targetId" TEXT,
  "metadata" TEXT,
  "ipHash" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "SavedItem" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "targetType" TEXT NOT NULL,
  "targetId" TEXT NOT NULL,
  "note" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("userId", "targetType", "targetId"),
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "ActivityLog" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "targetType" TEXT,
  "targetId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "UserBlock" (
  "id" TEXT PRIMARY KEY,
  "blockerId" TEXT NOT NULL,
  "blockedId" TEXT NOT NULL,
  "reason" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("blockerId", "blockedId"),
  FOREIGN KEY ("blockerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("blockedId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Category" (
  "id" TEXT PRIMARY KEY,
  "kind" TEXT NOT NULL,
  "key" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "description" TEXT,
  "icon" TEXT,
  "position" INTEGER NOT NULL DEFAULT 0,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("kind", "key")
);

CREATE TABLE "SiteSetting" (
  "id" TEXT PRIMARY KEY,
  "key" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  UNIQUE ("key")
);

CREATE TABLE "File" (
  "id" TEXT PRIMARY KEY,
  "ownerId" TEXT NOT NULL,
  "groupId" TEXT,
  "tripId" TEXT,
  "businessId" TEXT,
  "targetType" TEXT,
  "targetId" TEXT,
  "storedName" TEXT NOT NULL,
  "originalName" TEXT NOT NULL,
  "mimeType" TEXT NOT NULL,
  "sizeBytes" INTEGER NOT NULL,
  "sha256" TEXT,
  "storage" TEXT NOT NULL DEFAULT 'local',
  "storageKey" TEXT NOT NULL,
  "deletedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("businessId") REFERENCES "BusinessProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "User_role_idx" ON "User" ("role");

CREATE INDEX "User_createdAt_idx_1" ON "User" ("createdAt");

CREATE INDEX "Account_userId_idx" ON "Account" ("userId");

CREATE INDEX "Session_userId_idx" ON "Session" ("userId");

CREATE INDEX "Session_expiresAt_idx_1" ON "Session" ("expiresAt");

CREATE INDEX "Profile_city_idx" ON "Profile" ("city");

CREATE INDEX "Profile_verificationStatus_idx_1" ON "Profile" ("verificationStatus");

CREATE INDEX "Group_visibility_idx" ON "Group" ("visibility");

CREATE INDEX "Group_ownerId_idx_1" ON "Group" ("ownerId");

CREATE INDEX "Task_ownerId_completedAt_idx" ON "Task" ("ownerId", "completedAt");

CREATE INDEX "Task_dueAt_idx_1" ON "Task" ("dueAt");

CREATE INDEX "Task_groupId_idx_2" ON "Task" ("groupId");

CREATE INDEX "Subtask_taskId_idx" ON "Subtask" ("taskId");

CREATE INDEX "Note_ownerId_pinned_idx" ON "Note" ("ownerId", "pinned");

CREATE INDEX "Habit_ownerId_idx" ON "Habit" ("ownerId");

CREATE INDEX "Bookmark_ownerId_favorite_idx" ON "Bookmark" ("ownerId", "favorite");

CREATE INDEX "Trip_ownerId_idx" ON "Trip" ("ownerId");

CREATE INDEX "Trip_visibility_idx_1" ON "Trip" ("visibility");

CREATE INDEX "CalendarEvent_ownerId_startsAt_idx" ON "CalendarEvent" ("ownerId", "startsAt");

CREATE INDEX "GroupMember_userId_idx" ON "GroupMember" ("userId");

CREATE INDEX "GroupInvitation_groupId_idx" ON "GroupInvitation" ("groupId");

CREATE INDEX "GroupPost_groupId_createdAt_idx" ON "GroupPost" ("groupId", "createdAt");

CREATE INDEX "ShoppingItem_groupId_purchasedAt_idx" ON "ShoppingItem" ("groupId", "purchasedAt");

CREATE INDEX "HelpRequest_status_createdAt_idx" ON "HelpRequest" ("status", "createdAt");

CREATE INDEX "HelpRequest_category_idx_1" ON "HelpRequest" ("category");

CREATE INDEX "HelpRequest_city_idx_2" ON "HelpRequest" ("city");

CREATE INDEX "HelpRequest_authorId_idx_3" ON "HelpRequest" ("authorId");

CREATE INDEX "HelpResponse_requestId_idx" ON "HelpResponse" ("requestId");

CREATE INDEX "Comment_targetType_targetId_idx" ON "Comment" ("targetType", "targetId");

CREATE INDEX "Comment_authorId_idx_1" ON "Comment" ("authorId");

CREATE INDEX "Vote_targetType_targetId_idx" ON "Vote" ("targetType", "targetId");

CREATE INDEX "StudentResource_subjectId_idx" ON "StudentResource" ("subjectId");

CREATE INDEX "StudentResource_level_difficulty_idx_1" ON "StudentResource" ("level", "difficulty");

CREATE INDEX "StudentResource_uploaderId_idx_2" ON "StudentResource" ("uploaderId");

CREATE INDEX "FlashcardDeck_ownerId_idx" ON "FlashcardDeck" ("ownerId");

CREATE INDEX "Flashcard_deckId_idx" ON "Flashcard" ("deckId");

CREATE INDEX "Flashcard_ownerId_nextReviewAt_idx_1" ON "Flashcard" ("ownerId", "nextReviewAt");

CREATE INDEX "Assignment_ownerId_dueAt_idx" ON "Assignment" ("ownerId", "dueAt");

CREATE INDEX "Exam_ownerId_examAt_idx" ON "Exam" ("ownerId", "examAt");

CREATE INDEX "TimetableSlot_ownerId_dayOfWeek_idx" ON "TimetableSlot" ("ownerId", "dayOfWeek");

CREATE INDEX "CourseGrade_ownerId_idx" ON "CourseGrade" ("ownerId");

CREATE INDEX "Listing_kind_published_idx" ON "Listing" ("kind", "published");

CREATE INDEX "Listing_deadline_idx_1" ON "Listing" ("deadline");

CREATE INDEX "SkillOffer_skillId_isActive_idx" ON "SkillOffer" ("skillId", "isActive");

CREATE INDEX "SkillOffer_userId_idx_1" ON "SkillOffer" ("userId");

CREATE INDEX "SkillRequest_skillId_isActive_idx" ON "SkillRequest" ("skillId", "isActive");

CREATE INDEX "SkillRequest_userId_idx_1" ON "SkillRequest" ("userId");

CREATE INDEX "SkillConnection_toUserId_status_idx" ON "SkillConnection" ("toUserId", "status");

CREATE INDEX "SkillConnection_fromUserId_idx_1" ON "SkillConnection" ("fromUserId");

CREATE INDEX "SkillReview_revieweeId_idx" ON "SkillReview" ("revieweeId");

CREATE INDEX "LocalResource_category_status_idx" ON "LocalResource" ("category", "status");

CREATE INDEX "LocalResource_city_idx_1" ON "LocalResource" ("city");

CREATE INDEX "ResourceReview_resourceId_idx" ON "ResourceReview" ("resourceId");

CREATE INDEX "ResourceEditSuggestion_resourceId_status_idx" ON "ResourceEditSuggestion" ("resourceId", "status");

CREATE INDEX "VolunteerOpportunity_status_createdAt_idx" ON "VolunteerOpportunity" ("status", "createdAt");

CREATE INDEX "VolunteerOpportunity_cause_idx_1" ON "VolunteerOpportunity" ("cause");

CREATE INDEX "VolunteerOpportunity_city_idx_2" ON "VolunteerOpportunity" ("city");

CREATE INDEX "DonationCampaign_status_createdAt_idx" ON "DonationCampaign" ("status", "createdAt");

CREATE INDEX "DonationCampaign_cause_idx_1" ON "DonationCampaign" ("cause");

CREATE INDEX "CampaignUpdate_campaignId_idx" ON "CampaignUpdate" ("campaignId");

CREATE INDEX "BloodDonorProfile_bloodGroup_city_idx" ON "BloodDonorProfile" ("bloodGroup", "city");

CREATE INDEX "EmergencyNumber_country_service_idx" ON "EmergencyNumber" ("country", "service");

CREATE INDEX "EmergencyContact_userId_idx" ON "EmergencyContact" ("userId");

CREATE INDEX "Guide_kind_published_idx" ON "Guide" ("kind", "published");

CREATE INDEX "MissingPerson_status_createdAt_idx" ON "MissingPerson" ("status", "createdAt");

CREATE INDEX "Service_businessId_idx" ON "Service" ("businessId");

CREATE INDEX "Customer_businessId_idx" ON "Customer" ("businessId");

CREATE INDEX "InventoryItem_businessId_idx" ON "InventoryItem" ("businessId");

CREATE INDEX "Appointment_businessId_startsAt_idx" ON "Appointment" ("businessId", "startsAt");

CREATE INDEX "Invoice_businessId_status_idx" ON "Invoice" ("businessId", "status");

CREATE INDEX "InvoiceItem_invoiceId_idx" ON "InvoiceItem" ("invoiceId");

CREATE INDEX "SaleRecord_businessId_soldAt_idx" ON "SaleRecord" ("businessId", "soldAt");

CREATE INDEX "CannedMessage_businessId_idx" ON "CannedMessage" ("businessId");

CREATE INDEX "ItineraryItem_tripId_position_idx" ON "ItineraryItem" ("tripId", "position");

CREATE INDEX "PackingItem_tripId_idx" ON "PackingItem" ("tripId");

CREATE INDEX "Expense_ownerId_occurredOn_idx" ON "Expense" ("ownerId", "occurredOn");

CREATE INDEX "Expense_groupId_idx_1" ON "Expense" ("groupId");

CREATE INDEX "Expense_tripId_idx_2" ON "Expense" ("tripId");

CREATE INDEX "Expense_businessId_idx_3" ON "Expense" ("businessId");

CREATE INDEX "ExpenseSplit_userId_idx" ON "ExpenseSplit" ("userId");

CREATE INDEX "Poll_groupId_idx" ON "Poll" ("groupId");

CREATE INDEX "Poll_tripId_idx_1" ON "Poll" ("tripId");

CREATE INDEX "PollOption_pollId_idx" ON "PollOption" ("pollId");

CREATE INDEX "PollVote_userId_idx" ON "PollVote" ("userId");

CREATE INDEX "Conversation_lastMessageAt_idx" ON "Conversation" ("lastMessageAt");

CREATE INDEX "ConversationParticipant_userId_idx" ON "ConversationParticipant" ("userId");

CREATE INDEX "Message_conversationId_createdAt_idx" ON "Message" ("conversationId", "createdAt");

CREATE INDEX "Notification_userId_readAt_idx" ON "Notification" ("userId", "readAt");

CREATE INDEX "Notification_userId_createdAt_idx_1" ON "Notification" ("userId", "createdAt");

CREATE INDEX "Report_status_createdAt_idx" ON "Report" ("status", "createdAt");

CREATE INDEX "Report_targetType_targetId_idx_1" ON "Report" ("targetType", "targetId");

CREATE INDEX "ModerationAction_targetType_targetId_idx" ON "ModerationAction" ("targetType", "targetId");

CREATE INDEX "ModerationAction_moderatorId_idx_1" ON "ModerationAction" ("moderatorId");

CREATE INDEX "AuditLog_action_createdAt_idx" ON "AuditLog" ("action", "createdAt");

CREATE INDEX "AuditLog_actorId_idx_1" ON "AuditLog" ("actorId");

CREATE INDEX "ActivityLog_userId_createdAt_idx" ON "ActivityLog" ("userId", "createdAt");

CREATE INDEX "File_ownerId_idx" ON "File" ("ownerId");

CREATE INDEX "File_targetType_targetId_idx_1" ON "File" ("targetType", "targetId");
