import type { Metadata } from 'next';
import { Card, CardContent, CardHeader, SectionHeading } from '@/components/ui/card';
import { Alert } from '@/components/ui/feedback';

export const metadata: Metadata = { title: 'Privacy' };

export default function PrivacyPage() {
  return (
    <div className="mx-auto grid w-full max-w-4xl gap-6 px-4 py-12">
      <SectionHeading
        title="Privacy"
        description="What OpenHub stores, what it never stores, and how you control it."
      />

      <Alert tone="info">
        This page describes the software. If you use an instance run by someone else, that operator is the data controller and may
        have additional obligations — ask them for their contact details and retention policy.
      </Alert>

      <Card>
        <CardHeader title="What we store" />
        <CardContent>
          <ul className="grid gap-2 text-sm text-muted-foreground">
            <li>Account details: email, username, a scrypt password hash, role, last login time.</li>
            <li>Profile details you choose to add: display name, bio, city, website, member types, skills, languages.</li>
            <li>Content you create: tasks, notes, habits, bookmarks, calendar events, expenses, help posts, comments, messages, uploads.</li>
            <li>Community records: group membership, votes, saved items, reports, moderation actions and the audit log.</li>
            <li>Sessions: a hashed token, device info and expiry, so you can sign out of other devices.</li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader title="What we never store" />
        <CardContent>
          <ul className="grid gap-2 text-sm text-muted-foreground">
            <li>Passwords in plain text — only a salted scrypt hash is kept.</li>
            <li>Anything generated by the utility tools: passwords, hashes, QR text, converted values stay in your browser.</li>
            <li>Payment card details. OpenHub has no payment processing; only an optional provider interface.</li>
            <li>Advertising identifiers, third-party analytics, or tracking pixels. None are included in the default deployment.</li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader title="Your controls" />
        <CardContent>
          <ul className="grid gap-2 text-sm text-muted-foreground">
            <li>Settings → Privacy: profile visibility, whether your city shows, whether you appear in search, who can message you, whether your group memberships show.</li>
            <li>Settings → Security & data: change your password, download everything we store about you as JSON, delete your account.</li>
            <li>Any post: choose public or private visibility, and delete or edit it later.</li>
            <li>Any member: block them, which hides you from them immediately.</li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader title="Who can see what" />
        <CardContent>
          <ul className="grid gap-2 text-sm text-muted-foreground">
            <li>Private profiles never appear in the member directory or search results.</li>
            <li>Local resources show a street-level address, never a member's home.</li>
            <li>Messages are readable only by participants. Moderators see them only through a report.</li>
            <li>Search respects every privacy flag: private notes, private help posts and unpublished listings never appear.</li>
            <li>Moderators and administrators see content when reviewing reports. Every privileged action is written to the audit log.</li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader title="Optional services" />
        <CardContent>
          <ul className="grid gap-2 text-sm text-muted-foreground">
            <li>Email (SMTP or Resend) — only if configured. Used for verification and digests you enable.</li>
            <li>Object storage (S3-compatible) — only if configured. Otherwise uploads stay on the local disk.</li>
            <li>Currency rates — only if you set an API key. The converter works without it.</li>
            <li>Maps — generated as plain links to OpenStreetMap or Google Maps. No key, no tracking.</li>
            <li>Redis — optional, only for shared rate limiting across instances.</li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader title="Retention and deletion" />
        <CardContent>
          <ul className="grid gap-2 text-sm text-muted-foreground">
            <li>Deleting your account removes your profile, content and sessions. Sessions end immediately.</li>
            <li>Moderation and audit records are kept because they document decisions about abuse.</li>
            <li>Self-hosted operators decide their own backup and retention policy — nothing is sent anywhere else by default.</li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardContent className="py-5 text-sm text-muted-foreground">
          Questions about this software's privacy behaviour? Open an issue in the repository. Questions about data held by a specific
          instance? Contact that instance's administrator.
        </CardContent>
      </Card>
    </div>
  );
}
