import { mkdir, writeFile, unlink } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { randomBytes } from 'node:crypto';
import { getDb } from '@/server/db/client';
import { env } from '@/lib/env';
import { ALLOWED_UPLOAD_MIME_TYPES, MAX_UPLOAD_BYTES } from '@/lib/enums';
import { sha256 } from '@/lib/security';
import { ValidationError } from '@/lib/errors';

/**
 * File storage abstraction.
 *
 * The default provider writes to a local directory (mounted volume in Docker).
 * The interface is deliberately small so an S3/WebDAV provider can be added
 * without touching call sites.
 *
 * Security notes:
 *  - the stored filename is generated by OpenHub, never taken from the client
 *  - mime type and size are validated before anything touches disk
 *  - files are served through an authorized route, not as public static assets
 */

export interface StorageProvider {
  readonly name: string;
  put(key: string, data: Uint8Array): Promise<void>;
  get(key: string): Promise<Uint8Array | null>;
  remove(key: string): Promise<void>;
}

class LocalStorageProvider implements StorageProvider {
  readonly name = 'local';
  private root: string;

  constructor() {
    this.root = resolve(process.cwd(), env().UPLOAD_DIR);
  }

  private pathFor(key: string): string {
    const target = resolve(this.root, key);
    if (!target.startsWith(this.root)) throw new ValidationError('Invalid file path.');
    return target;
  }

  async put(key: string, data: Uint8Array): Promise<void> {
    const target = this.pathFor(key);
    await mkdir(join(target, '..'), { recursive: true });
    await writeFile(target, data);
  }

  async get(key: string): Promise<Uint8Array | null> {
    const { readFile } = await import('node:fs/promises');
    try {
      return await readFile(this.pathFor(key));
    } catch {
      return null;
    }
  }

  async remove(key: string): Promise<void> {
    try {
      await unlink(this.pathFor(key));
    } catch {
      // Already gone - nothing to do.
    }
  }
}

export function storageProvider(): StorageProvider {
  if (env().STORAGE_PROVIDER === 's3') {
    throw new Error(
      'S3 storage is not bundled. Set STORAGE_PROVIDER=local or implement StorageProvider for your object store.',
    );
  }
  return new LocalStorageProvider();
}

/** Strip directories and unsafe characters; never trust the client filename. */
export function safeFileName(originalName: string, mimeType: string): { name: string; extension: string } {
  const base = originalName.split(/[\\/]/).pop() ?? 'file';
  const cleaned = base
    .normalize('NFKD')
    .replace(/[^\w.\- ]/g, '')
    .replace(/\s+/g, '-')
    .slice(0, 60)
    .replace(/^[-.]+/, '') || 'file';
  const extensionMap: Record<string, string> = {
    'image/jpeg': 'jpg',
    'image/png': 'png',
    'image/webp': 'webp',
    'image/gif': 'gif',
    'application/pdf': 'pdf',
    'text/plain': 'txt',
    'text/markdown': 'md',
    'text/csv': 'csv',
  };
  const extension = extensionMap[mimeType] ?? 'bin';
  return { name: cleaned, extension };
}

export type UploadInput = {
  ownerId: string;
  file: File;
  targetType?: string | null;
  targetId?: string | null;
  groupId?: string | null;
  tripId?: string | null;
  businessId?: string | null;
};

export async function storeUpload(input: UploadInput) {
  if (input.file.size > MAX_UPLOAD_BYTES) {
    throw new ValidationError(`Files must be smaller than ${MAX_UPLOAD_BYTES / 1024 / 1024} MB.`);
  }
  const allowed = ALLOWED_UPLOAD_MIME_TYPES as readonly string[];
  if (!allowed.includes(input.file.type)) {
    throw new ValidationError('That file type is not allowed. Images, PDF, CSV, TXT and Markdown are supported.');
  }

  const buffer = Buffer.from(await input.file.arrayBuffer());
  const { name, extension } = safeFileName(input.file.name, input.file.type);
  const storedName = `${Date.now().toString(36)}-${randomBytes(6).toString('hex')}.${extension}`;
  const storageKey = `${new Date().toISOString().slice(0, 7)}/${storedName}`;

  await storageProvider().put(storageKey, new Uint8Array(buffer));

  const db = await getDb();
  return db.file.create({
    data: {
      ownerId: input.ownerId,
      groupId: input.groupId ?? null,
      tripId: input.tripId ?? null,
      businessId: input.businessId ?? null,
      targetType: input.targetType ?? null,
      targetId: input.targetId ?? null,
      storedName,
      originalName: name.slice(0, 120),
      mimeType: input.file.type,
      sizeBytes: input.file.size,
      sha256: sha256(buffer),
      storage: storageProvider().name,
      storageKey,
    },
  });
}

export async function readFileRecord(fileId: string) {
  const db = await getDb();
  const record = await db.file.findUnique({ where: { id: fileId } });
  if (!record || record.deletedAt) return null;
  const data = await storageProvider().get(record.storageKey);
  return data ? { record, data } : null;
}

export async function deleteFileRecord(fileId: string, actorId: string): Promise<void> {
  const db = await getDb();
  const record = await db.file.findUnique({ where: { id: fileId } });
  if (!record) return;
  if (record.ownerId !== actorId) {
    const { requireStaff } = await import('@/server/core/guards');
    await requireStaff();
  }
  await storageProvider().remove(record.storageKey);
  await db.file.update({ where: { id: fileId }, data: { deletedAt: new Date() } });
}
