import {
  LayoutDashboard,
  Search,
  Bell,
  MessageSquare,
  CheckSquare,
  NotebookPen,
  Repeat,
  Calendar,
  CalendarDays,
  Wallet,
  Bookmark,
  Timer,
  LifeBuoy,
  Users,
  MapPin,
  HandHeart,
  GraduationCap,
  BookOpen,
  Shield,
  ShieldCheck,
  Luggage,
  Store,
  Wrench,
  Heart,
  History,
  Settings,
  Menu,
  Sun,
  Moon,
  Plus,
  Trash2,
  Pencil,
  Flag,
  Share2,
  Download,
  Upload,
  Filter,
  MoreHorizontal,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ExternalLink,
  AlertTriangle,
  Info,
  Check,
  X,
  Printer,
  QrCode,
  Sparkles,
  Clock,
  TrendingUp,
  FileText,
  Package,
  UserPlus,
  LogOut,
  KeyRound,
  Eye,
  EyeOff,
  Send,
  ArrowLeft,
  ArrowRight,
  type LucideIcon,
} from 'lucide-react';

/**
 * Icon registry.
 *
 * Navigation and dashboard widgets reference icons by stable string keys so the
 * config stays serialisable; this map is the only place that touches lucide.
 */
const icons: Record<string, LucideIcon> = {
  'layout-dashboard': LayoutDashboard,
  search: Search,
  bell: Bell,
  'message-square': MessageSquare,
  'check-square': CheckSquare,
  'notebook-pen': NotebookPen,
  repeat: Repeat,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  wallet: Wallet,
  bookmark: Bookmark,
  timer: Timer,
  'life-buoy': LifeBuoy,
  users: Users,
  'map-pin': MapPin,
  'hand-heart': HandHeart,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  shield: Shield,
  'shield-check': ShieldCheck,
  luggage: Luggage,
  store: Store,
  wrench: Wrench,
  heart: Heart,
  history: History,
  settings: Settings,
  menu: Menu,
  sun: Sun,
  moon: Moon,
  plus: Plus,
  trash: Trash2,
  pencil: Pencil,
  flag: Flag,
  share: Share2,
  download: Download,
  upload: Upload,
  filter: Filter,
  more: MoreHorizontal,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'external-link': ExternalLink,
  warning: AlertTriangle,
  info: Info,
  check: Check,
  close: X,
  printer: Printer,
  qr: QrCode,
  sparkles: Sparkles,
  clock: Clock,
  trending: TrendingUp,
  file: FileText,
  package: Package,
  'user-plus': UserPlus,
  logout: LogOut,
  key: KeyRound,
  eye: Eye,
  'eye-off': EyeOff,
  send: Send,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
};

export function Icon({
  name,
  className = 'h-4 w-4',
  strokeWidth = 2,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Component = icons[name] ?? Info;
  return <Component className={className} strokeWidth={strokeWidth} aria-hidden="true" focusable="false" />;
}

export { icons };
